"""Create characters and snapshots tables

Revision ID: c6d149f4a81b
Revises: 
Create Date: 2026-04-24 15:31:27.911169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d149f4a81b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=4), nullable=False),
    sa.Column('realm_slug', sa.String(length=64), nullable=False),
    sa.Column('name_slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'realm_slug', 'name_slug', name='uq_character_identity')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_id', sa.String(length=8), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('mythic_rating', sa.Float(), nullable=False),
    sa.Column('weekly_run_count', sa.Integer(), nullable=False),
    sa.Column('vault_slot_1_level', sa.Integer(), nullable=True),
    sa.Column('vault_slot_2_level', sa.Integer(), nullable=True),
    sa.Column('vault_slot_3_level', sa.Integer(), nullable=True),
    sa.Column('vault_slot_1_ilvl', sa.Integer(), nullable=True),
    sa.Column('vault_slot_2_ilvl', sa.Integer(), nullable=True),
    sa.Column('vault_slot_3_ilvl', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_character_week', 'snapshots', ['character_id', 'week_id'], unique=False)
    op.create_index('ix_snapshot_taken_at', 'snapshots', ['taken_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_taken_at', table_name='snapshots')
    op.drop_index('ix_snapshot_character_week', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('characters')
    # ### end Alembic commands ###
